// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchPaymentsHandlerFunc turns a function with the right signature into a patch payments handler
type PatchPaymentsHandlerFunc func(PatchPaymentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchPaymentsHandlerFunc) Handle(params PatchPaymentsParams) middleware.Responder {
	return fn(params)
}

// PatchPaymentsHandler interface for that can handle valid patch payments params
type PatchPaymentsHandler interface {
	Handle(PatchPaymentsParams) middleware.Responder
}

// NewPatchPayments creates a new http.Handler for the patch payments operation
func NewPatchPayments(ctx *middleware.Context, handler PatchPaymentsHandler) *PatchPayments {
	return &PatchPayments{Context: ctx, Handler: handler}
}

/*PatchPayments swagger:route PATCH /payments patchPayments

PatchPayments patch payments API

*/
type PatchPayments struct {
	Context *middleware.Context
	Handler PatchPaymentsHandler
}

func (o *PatchPayments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchPaymentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
