// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pawmart/form3-payments/models"
)

// PostPaymentsCreatedCode is the HTTP code returned for type PostPaymentsCreated
const PostPaymentsCreatedCode int = 201

/*PostPaymentsCreated Payment creation response

swagger:response postPaymentsCreated
*/
type PostPaymentsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.PaymentCreationResponse `json:"body,omitempty"`
}

// NewPostPaymentsCreated creates PostPaymentsCreated with default headers values
func NewPostPaymentsCreated() *PostPaymentsCreated {

	return &PostPaymentsCreated{}
}

// WithPayload adds the payload to the post payments created response
func (o *PostPaymentsCreated) WithPayload(payload *models.PaymentCreationResponse) *PostPaymentsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post payments created response
func (o *PostPaymentsCreated) SetPayload(payload *models.PaymentCreationResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPaymentsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPaymentsBadRequestCode is the HTTP code returned for type PostPaymentsBadRequest
const PostPaymentsBadRequestCode int = 400

/*PostPaymentsBadRequest Payment creation error

swagger:response postPaymentsBadRequest
*/
type PostPaymentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostPaymentsBadRequest creates PostPaymentsBadRequest with default headers values
func NewPostPaymentsBadRequest() *PostPaymentsBadRequest {

	return &PostPaymentsBadRequest{}
}

// WithPayload adds the payload to the post payments bad request response
func (o *PostPaymentsBadRequest) WithPayload(payload *models.APIError) *PostPaymentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post payments bad request response
func (o *PostPaymentsBadRequest) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPaymentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPaymentsInternalServerErrorCode is the HTTP code returned for type PostPaymentsInternalServerError
const PostPaymentsInternalServerErrorCode int = 500

/*PostPaymentsInternalServerError Fatal error

swagger:response postPaymentsInternalServerError
*/
type PostPaymentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostPaymentsInternalServerError creates PostPaymentsInternalServerError with default headers values
func NewPostPaymentsInternalServerError() *PostPaymentsInternalServerError {

	return &PostPaymentsInternalServerError{}
}

// WithPayload adds the payload to the post payments internal server error response
func (o *PostPaymentsInternalServerError) WithPayload(payload *models.APIError) *PostPaymentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post payments internal server error response
func (o *PostPaymentsInternalServerError) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPaymentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
