// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Form3 Payments API Test - Pawel Martuszewski

    Schemes:
      http
    Host: localhost:6543
    BasePath: /v1
    Version: 1

    Consumes:
    - application/json
    - application/octet-stream

    Produces:
    - application/json

swagger:meta
*/
package restapi
